language: node_js
node_js: stable

branches:
  only:
  - hexo-source

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - export TZ='Asia/Shanghai'

install:
  - yarn global add hexo-cli
  - yarn

script:
#  - hexo clean
  - hexo generate

# after_success:
 # - git config --global user.name "$GIT_NAME"
 # - git config --global user.email "$GIT_EMAIL"
 # - sed -i "s/GH_TOKEN/$GH_TOKEN/g" ./_config.yml
 # - sed -i "s/CODING_TOKEN/$CODING_TOKEN/g" ./_config.yml
 # - cat ./_config.yml
 # - hexo deploy -m "Travis CI Build ${TRAVIS_BUILD_NUMBER}"

deploy:
  provider: pages
  skip_cleanup: true # 跳过清理
  local_dir: public # 需要推送到Github的静态文件目录 
#  name: $GIT_NAME # 用户名变量
#  email: $GIT_EMAIL # 用户邮箱变量
  github_token: $GH_TOKEN # GitHub Token变量
  keep-history: true # 保持推送记录，以增量提交的方式
  target-branch: master # 推送的目标分支 local_dir->>master分支
  on:
    branch: hexo-source # 工作分支

notifications:
email:
  recipients:
    - $GIT_EMAIL
  on_success: change # default: change
  on_failure: always # default: always