language: python
python: 3.7

branches:
  only:
  - src
before_install:
  - sudo apt-get update -qq
  - sudo apt-get -yq install apt-transport-https

  # install - install any dependencies required
install:
  # install latest hugo release version
  - wget -qO- https://api.github.com/repos/gohugoio/hugo/releases/latest | sed -r -n '/browser_download_url/{/Linux-64bit.deb/{s@[^:]*:[[:space:]]*"([^"]*)".*@\1@g;p;q}}' | xargs wget
  - sudo dpkg -i hugo*.deb
  - rm -rf public 2> /dev/null

script:
  - hugo --gc --minify

after_success:
  - cd public
  - git config --global user.name $GIT_NAME
  - git config --global user.email $GIT_EMAIL
  - git init
  - git add .
  - git commit -m "Travis CI Build ${TRAVIS_BUILD_NUMBER}"
  - git push --force "https://${GH_TOKEN}@github.com/lei2rock/homepage.git" master:master

notifications:
  email:
    recipients:
      - $GIT_EMAIL
    on_success: change
    on_failure: always