# ---------------------------------------------------------------
# Theme Core Configuration Settings
# See: https://theme-next.js.org/docs/theme-settings/
# ---------------------------------------------------------------

minify: true

custom_file_path:
  variable: source/_data/variables.styl
  style: source/_data/styles.styl

# ---------------------------------------------------------------
# Scheme Settings
# ---------------------------------------------------------------

scheme: Gemini
darkmode: true
# Color style: Day of Mourning
gray: false

# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

favicon:
  small: /images/favicon-16x16.png
  medium: /images/favicon-32x32.png
  apple_touch_icon: /images/apple-touch-icon.png
  safari_pinned_tab: /images/safari-pinned-tab.svg

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

menu:
  About: / || fas fa-user-circle
  Contact: /contact/ || fas fa-paper-plane
  Blog Posts: https://blog.dlzhang.com/overview/tags/English/ || fas fa-feather-alt

# ---------------------------------------------------------------
# Sidebar Settings
# ---------------------------------------------------------------

site_state: false

social:
  Weibo: https://weibo.com/1156774800 || fab fa-weibo
  GitHub: https://github.com/lei2rock || fab fa-github

social_icons:
  icons_only: true

# ---------------------------------------------------------------
# Footer Settings
# ---------------------------------------------------------------

footer:
  since: 2015
  icon:
    name: fas fa-heart
    animated: true
    color: "#f06292"
  copyright: Zhang Donglei
  powered: false

# ---------------------------------------------------------------
# Misc Theme Settings
# ---------------------------------------------------------------

# Preconnect CDN for fonts and plugins.
preconnect: true

android_chrome_color: "#6c599f"

back2top:
  enable: true
  scrollpercent: true

# ---------------------------------------------------------------
# Font Settings
# ---------------------------------------------------------------

font:
  enable: true
  global:
    family: EB Garamond, Noto Serif SC
  title:
    family: Fondamento
  headings:
    size: 1.48

# ---------------------------------------------------------------
# SEO Settings
# ---------------------------------------------------------------

disable_baidu_transformation: true
google_site_verification: SJUudYL5q_atXSgew2qwy69FXOnSnNB2rAmwHmcBT9U
baidu_site_verification: 2QXEpIlRcv

# ---------------------------------------------------------------
# Third Party Plugins & Services Settings
# ---------------------------------------------------------------

pjax: true
fancybox: true
lazyload: true
pangu: true

# ---------------------------------------------------------------
# Statistics and Analytics
# ---------------------------------------------------------------

google_analytics:
  tracking_id: UA-141207776-2

# ---------------------------------------------------------------
# Tags Settings
# ---------------------------------------------------------------

note:
  style: simple
  icons: true

# ---------------------------------------------------------------
# Animation Settings
# ---------------------------------------------------------------

motion:
  enable: false
