# ************************************************************************************************************
# ************************************************************************************************************
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/
# ************************************************************************************************************
# ************************************************************************************************************

# Site
title: Zhang Donglei
subtitle:
description: <div>Never say you know the essence,</div><div>let alone the truth.</div><div>无曰已是，无曰遂真。</div><div>― Zhejiang University Anthem</div>
keywords: [Donglei, 张栋磊, cuhk, zju, economics]
author:
language: en
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://dlzhang.com
root: /
permalink: /posts/:year/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: overview/tags
archive_dir: archives
category_dir: overview
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md
  - 404.html

# Writing
new_post_name: :year/:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: true
  tab_replace: true
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: posts
  per_page: 15
  order_by: -date

# Category & Tag
default_category: Ramble
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 20
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

## Hexo server module
## Use `hexo server`
server:
  ip: 127.0.0.1


# ************************************************************************************************************
# ************************************************************************************************************
# Theme Core Configuration Settings
# See: https://theme-next.org/docs/theme-settings/
# ************************************************************************************************************
# ************************************************************************************************************

theme_config:

  minify: true

  # Create your custom files in site directory `source/_data` and uncomment needed files below.
  custom_file_path:
    head: source/_data/head.swig
  #  header: source/_data/header.swig
  #  sidebar: source/_data/sidebar.swig
    postMeta: source/_data/post-meta.swig
  #  postBodyEnd: source/_data/post-body-end.swig
  #  footer: source/_data/footer.swig
    bodyEnd: source/_data/body-end.swig
    variable: source/_data/variables.styl
    mixin: source/_data/mixins.styl
    style: source/_data/styles.styl

  # ---------------------------------------------------------------
  # Site Information Settings
  # See: https://theme-next.org/docs/getting-started/
  # ---------------------------------------------------------------

  favicon:
    small: https://web-1256060851.file.myqcloud.com/assets/img/favicon-16x16.png
    medium: https://web-1256060851.file.myqcloud.com/assets/img/favicon-32x32.png
    apple_touch_icon: https://web-1256060851.file.myqcloud.com/assets/img/apple-touch-icon.png
    safari_pinned_tab: https://web-1256060851.file.myqcloud.com/assets/img/safari-pinned-tab.svg

  footer:
    since: 2015
    icon:
      name: fas fa-heart
      animated: true
      color: '#f06292'
    copyright: Zhang Donglei
    powered: false

  # ---------------------------------------------------------------
  # Scheme Settings
  # ---------------------------------------------------------------

  scheme: Gemini
  darkmode: true

  # ---------------------------------------------------------------
  # Menu Settings
  # ---------------------------------------------------------------

  menu:
    home: / || fas fa-user-circle
    research: /research/ || fas fa-university
    posts: /posts/ || fas fa-feather-alt
    overview: 
      default: /overview/ || fas fa-th
      series: series/ || fas fa-cube
      tags: tags/ || fas fa-tags
    contact: /contact/ || fas fa-paper-plane

  # ---------------------------------------------------------------
  # Sidebar Settings
  # See: https://theme-next.org/docs/theme-settings/sidebar
  # ---------------------------------------------------------------

  # Posts / Categories / Tags in sidebar.
  site_state: false

  social:
    Weibo: https://weibo.com/1156774800 || fab fa-weibo
    Twitter: https://twitter.com/lei2rock || fab fa-twitter
    GitHub: https://github.com/lei2rock || fab fa-github
    RSS: /atom.xml || fa fa-rss

  social_icons:
    icons_only: true

  # Table of Contents in the Sidebar
  toc:
    # Automatically add list number to toc.
    number: false
    # If true, all words will placed on next lines if header width longer then sidebar width.
    wrap: true

  # ---------------------------------------------------------------
  # Post Settings
  # See: https://theme-next.org/docs/theme-settings/posts
  # ---------------------------------------------------------------

  read_more_btn: false

  post_meta:
    item_text: false
    updated_at:
      enable: false

  # Use icon instead of the symbol # to indicate the tag at the bottom of the post
  tag_icon: true

  reward_settings:
    # If true, reward will be displayed in every article by default.
    enable: true
    comment: 🍵 Buy me a cup of tea!

  reward:
    wechatpay: https://web-1256060851.file.myqcloud.com/images/wechat-pay.jpg
    alipay: https://web-1256060851.file.myqcloud.com/images/alipay.jpg

  # Dependencies: https://github.com/tea3/hexo-related-popular-posts
  related_posts:
    enable: true

  # Post edit
  # Dependencies: https://github.com/hexojs/hexo-deployer-git
  post_edit:
    enable: true
    url: https://github.com/lei2rock/homepage/tree/src/source/ # Link for view source

  # Show previous post and next post in post footer if exists
  # Available values: left | right | false
  post_navigation: right

  # ---------------------------------------------------------------
  # Custom Page Settings
  # See: https://theme-next.org/docs/theme-settings/custom-pages
  # ---------------------------------------------------------------

  # TagCloud settings for tags page.
  tagcloud:
    min: 12 # Minimun font size in px
    max: 30 # Maxium font size in px
    start: "#aaa" # Start color (hex, rgba, hsla or color keywords)
    end: "#111" # End color (hex, rgba, hsla or color keywords)
    amount: 200 # Amount of tags, change it if you have more than 200 tags

  # ---------------------------------------------------------------
  # Misc Theme Settings
  # ---------------------------------------------------------------

  # Set the text alignment in posts / pages.
  text_align:
    # Available values: start | end | left | right | center | justify | justify-all | match-parent
    desktop: left
    mobile: left

  # Android Chrome header panel color ($brand-bg / $headband-bg => $black-deep).
  android_chrome_color: "#6c599f"

  codeblock:
    # Code Highlight theme
    # Available values: normal | night | night eighties | night blue | night bright | solarized | solarized dark | galactic
    # See: https://github.com/chriskempson/tomorrow-theme
    highlight_theme: night
    # Add copy button on codeblock
    copy_button:
      enable: true
      # Show text copy result.
      show_result: true
      # Available values: default | flat | mac
      style: mac

  back2top:
    enable: true
    # Back to top in sidebar.
    sidebar: false
    # Scroll percent label in b2t button.
    scrollpercent: true

  # ---------------------------------------------------------------
  # Font Settings
  # See: https://theme-next.org/docs/theme-settings/#Fonts-Customization
  # ---------------------------------------------------------------

  font:
    enable: true

    # Uri of fonts host, e.g. https://fonts.googleapis.com (Default).
    host:

    # Font options:
    # `external: true` will load this font family from `host` above.
    # `family: Times New Roman`. Without any quotes.
    # `size: x.x`. Use `em` as unit. Default: 1 (16px)

    # Global font settings used for all elements inside <body>.
    global:
      external: true
      family: EB Garamond
      size:

    # Font settings for site title (.site-title).
    title:
      external: true
      family: Fondamento
      size:

    # Font settings for headlines (<h1> to <h6>).
    headings:
      external: true
      family: Noto Serif SC
      size: 1.48

    # Font settings for posts (.post-body).
    posts:
      external: true
      family:

    # Font settings for <code> and code blocks.
    codes:
      external: true
      family: Source Code Pro

  # ---------------------------------------------------------------
  # SEO Settings
  # ---------------------------------------------------------------

  google_site_verification: SJUudYL5q_atXSgew2qwy69FXOnSnNB2rAmwHmcBT9U
  disable_baidu_transformation: true
  baidu_site_verification: 2QXEpIlRcv
  baidu_push: true

  # ---------------------------------------------------------------
  # Third Party Plugins & Services Settings
  # See: https://theme-next.org/docs/third-party-services/
  # ---------------------------------------------------------------

  math:
    # hexo-renderer-pandoc (or hexo-renderer-kramed) required for full MathJax support.
    mathjax:
      enable: true

  pjax: true
  fancybox: true
  lazyload: true
  pangu: true

  # ---------------------------------------------------------------
  # Comments Settings
  # See: https://theme-next.org/docs/third-party-services/comments
  # ---------------------------------------------------------------

  # Valine
  # For more information: https://valine.js.org, https://github.com/xCss/Valine
  valine:
    enable: true
    appid: wJ0VIzaJuejbJjolt42SBxtF-MdYXbMMI # Your leancloud application appid
    appkey: 3od00D4hXsNwfgFWIbtMvLVO # Your leancloud application appkey
    placeholder: To receive reply notify, please provide E-Mail. # Comment box placeholder
    avatar: wavatar # Gravatar style
    guest_info: nick,mail # Custom comment header, nick,mail,link 
    pageSize: 5 # Pagination size
    language: en # Language, available values: en, zh-cn
    visitor: false # Article reading statistic
    comment_count: true # If false, comment count will only be displayed in post page, not in home page
    recordIP: true # Whether to record the commenter IP
    serverURLs: # When the custom domain name is enabled, fill it in here (it will be detected automatically by default, no need to fill in)
    #post_meta_order: 0

  # ---------------------------------------------------------------
  # Statistics and Analytics
  # See: https://theme-next.org/docs/third-party-services/statistics-and-analytics
  # ---------------------------------------------------------------

  # Google Analytics
  google_analytics:
    tracking_id: UA-141207776-2

  # Do not enable both `valine.visitor` and `leancloud_visitors`.
  leancloud_visitors:
    enable: true
    app_id: wJ0VIzaJuejbJjolt42SBxtF-MdYXbMMI # <your app id>
    app_key: 3od00D4hXsNwfgFWIbtMvLVO # <your app key>
    # Required for apps from CN region
    server_url: # <your server url>

  # ---------------------------------------------------------------
  # Search Services
  # See: https://theme-next.org/docs/third-party-services/search-services
  # ---------------------------------------------------------------

  # Dependencies: https://github.com/theme-next/hexo-generator-searchdb
  local_search:
    enable: true
    # If auto, trigger search by changing input.
    # If manual, trigger search by pressing enter key or search button.
    trigger: auto
    # Show top n results per article, show all results by setting to -1
    top_n_per_article: 1
    # Unescape html strings to the readable one.
    unescape: false
    # Preload the search data when the page loads.
    preload: true

  # ---------------------------------------------------------------
  # Tags Settings
  # See: https://theme-next.org/docs/tag-plugins/
  # ---------------------------------------------------------------

  # Note tag (bs-callout)
  note:
    style: simple
    icons: true
    # Offset lighter of background in % for modern and flat styles (modern: -12 | 12; flat: -18 | 6).
    # Offset also applied to label tag variables. This option can work with disabled note tag.
    light_bg_offset: 0

  # Tabs tag
  tabs:
    transition:
      tabs: true
      labels: true

  # ---------------------------------------------------------------
  # Animation Settings
  # ---------------------------------------------------------------

  # Use velocity to animate everything.
  motion:
    enable: false

  #! ---------------------------------------------------------------
  #! CDN: https://theme-next.org/docs/advanced-settings
  #! ---------------------------------------------------------------

  vendors:

    anime: https://cdn.jsdelivr.net/npm/animejs@3.1.0/lib/anime.min.js

    fontawesome: https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5/css/all.min.css

    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

    pjax: https://cdn.jsdelivr.net/gh/theme-next/theme-next-pjax@0/pjax.min.js

    jquery: https://cdn.jsdelivr.net/npm/jquery@3/dist/jquery.min.js
    fancybox: https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3/dist/jquery.fancybox.min.js
    fancybox_css: https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3/dist/jquery.fancybox.min.css

    lazyload: https://cdn.jsdelivr.net/npm/lozad@1/dist/lozad.min.js

    pangu: https://cdn.jsdelivr.net/npm/pangu@4/dist/browser/pangu.min.js

    # valine: https://cdn.jsdelivr.net/npm/valine@1/dist/Valine.min.js
    valine: https://cdn.jsdelivr.net/gh/xaoxuu/volantis@1.0/js/volantis.min.js

  # Assets
  css: https://web-1256060851.file.myqcloud.com/assets/homepage-css
  js: https://web-1256060851.file.myqcloud.com/assets/js
  images: https://web-1256060851.file.myqcloud.com/assets/img
