backend:
  name: git-gateway
  repo: lei2rock/homepage
  branch: hexo-source # Branch to update (master by default)

media_folder: "source/img" # Folder path where uploaded files should be saved, relative to the base of the repo.
public_folder: "/img" # Folder path where uploaded files will be accessed, relative to the base of the built site.

#publish_mode: editorial_workflow
site_url: https://dlzhang.com
display_url: https://dlzhang.com
logo_url: /img/logo.svg
show_preview_links: true
# slug:
#   encoding: "ascii" # default: unicode
#   clean_accents: true
#   sanitize_replacement: "_"  # default: "-"


collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "页面设置"
    files:
      - name: "about"
        label: "About"
        file: "/source/_posts/about.md"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "正文", name: "body", widget: "markdown"}
      - name: "research"
        label: "Research"
        file: "/source/research/index.md"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "正文", name: "body", widget: "markdown"}
      - name: "contact"
        label: "Contact"
        file: "/source/contact/index.md"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "正文", name: "body", widget: "markdown"}
      - name: "404"
        label: "404 页面"
        file: "/source/404/index.md"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "永久链接", name: "permalink", widget: "string", default: "/404"}
          - {label: "正文", name: "body", widget: "markdown"}
      - name: "readme_hexo"
        label: "README (hexo-source)"
        file: "/source/README.md"
        fields:
          - {label: "正文", name: "body", widget: "markdown"}
      - name: "readme_master"
        label: "README (master)"
        file: "/README.md"
        fields:
          - {label: "正文", name: "body", widget: "markdown"}