backend:
  name: git-gateway
  repo: dldylan/dldylan.github.io
  branch: hugo-source # Branch to update (master by default)

media_folder: "static/img" # Folder path where uploaded files should be saved, relative to the base of the repo.
public_folder: "/img" # Folder path where uploaded files will be accessed, relative to the base of the built site.

#publish_mode: editorial_workflow
site_url: https://dongleizhang.com
display_url: https://dongleizhang.com
logo_url: https://banbanramble-1256060851.cos.ap-shanghai.myqcloud.com/img/logo.svg
show_preview_links: true
# slug:
#   encoding: "ascii" # default: unicode
#   clean_accents: true
#   sanitize_replacement: "_"  # default: "-"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "科研动态" # Used in the UI, ie.: "New Post"
    folder: "/content/post" # The path to the folder where the documents are stored
    filter: {field: "type", value: "post"}
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "标题", name: "title", widget: "string"}
      - {label: "分类", name: "categories", widget: "list",, default: [""]}
      - {label: "标签", name: "tags", widget: "list", default: [""]}
      - {label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "LaTex", name: "math", widget: "boolean", default: false}
      - {label: "正文", name: "body", widget: "markdown"}
  - name: "pages"
    label: "分页设置"
    files:
      - file: "/content/author/admin/_index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "姓名", name: "name", widget: "string"}
          - {label: "科研兴趣", name: "interests", widget: "list",, default: [""]}
          - {label: "职位身份", name: "role", widget: "string"}
          - label: "所属组织机构"
            name: "organizations"
            widget: "list"
            fields:
              - {label: "组织名称", name: "name", widget: "string"}
              - {label: "链接", name: "url", widget: "string", default: "https://"}
          - label: "学习经历"
            name: "education"
            widget: "object"
            fields: 
              - label: "学位"
                name: "courses"
                widget: "list"
                allow_add: false
                fields:
                  - {label: "学位课程", name: "course", widget: "string"} 
                  - {label: "学校", name: "institution", widget: "string"} 
                  - {label: "毕业年份", name: "year", widget: "string"} 
          - label: "社交媒体"
            name: "social"
            widget: "list"
            fields:
              - {label: "图标", name: "icon", widget: "string"} 
              - {label: "图标库", name: "icon_pack", widget: "select", options: ["fab", "fas", "ai"]} 
              - {label: "链接", name: "link", widget: "string", default: "https://"} 
          - {label: "个人简介", name: "body", widget: "markdown"}
      - file: "/content/research/index.md"
        label: "Research"
        name: "research"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "正文", name: "body", widget: "markdown"}
      - file: "/content/contact/index.md"
        label: "Contact"
        name: "contact"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "正文", name: "body", widget: "markdown"}
      - file: "/config/_default/menus.toml"
        label: "Menu"
        name: "menu"
        fields:
          - label: "Main"
            name: "main"
            widget: "list"
            fields:
              - {label: "名称", name: "name", widget: "string"}
              - {label: "链接（首页插件用 #）", name: "url", widget: "string"}
              - {label: "次序", name: "weight", widget: "number", min: 1, step: 1}
