name: Deployment

on:
  push:
    braches: [src] # only push events on source branch trigger deployment

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
          submodules: true

#    - name: Setup Node.js for use with actions
#      uses: actions/setup-node@v1.1.0
#      with:
#          node-version: "10.x"

    # https://github.com/actions/cache/blob/master/examples.md#node---yarn
    - name: Get Yarn Cache Directory
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Cache Yarn
      uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install Dependencies
      run: |
        yarn global add hexo-cli
        yarn install

    - name: Generate Static Files
      run: |
        export PATH="$PATH:$(yarn global bin)"
        yarn build 
    #hexo generate && rm -rf public/melody-favicon.ico public/index.md/

    - name: Deploy to Github
      env:
        GIT_NAME: lei2rock
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        REPO: github.com/lei2rock/homepage
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

      run: |
        cd ./public && git init && git add .
        git config --global user.name $GIT_NAME
        git config --global user.email $GIT_EMAIL
        git commit -m "Site deployed by GitHub Actions"
        git push --force --quiet "https://${GH_TOKEN}@${REPO}" master:master
